# Generated by Django 4.1.7 on 2023-04-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='پست الکترونیک')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('fullname', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام و نام خوانوادگی')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت')),
                ('melli_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='users/profile', verbose_name='عکس پروفایل')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت کاربر')),
                ('is_admin', models.BooleanField(default=False, verbose_name='مدیر')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=155, null=True, verbose_name='توکن اعتبارسنجی')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('code', models.CharField(max_length=5, verbose_name=' کد فعالسازی')),
                ('expiration', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
            ],
            options={
                'verbose_name': 'کد اعتبارسنجی',
                'verbose_name_plural': 'کدهای اعتبارسنجی',
            },
        ),
    ]
