# Generated by Django 4.1.7 on 2023-04-17 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_melli_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordOtp',
            fields=[
                ('otp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.otp')),
            ],
            bases=('accounts.otp',),
        ),
    ]
